title: Gamecock Robotics
description: >-
  University of South Carolina's (UofSC) VEXU Robotics Team
# baseurl: "/GamecockRobotics.github.io" # the subpath of your site, e.g. /blog
# url: "https://GamecockRobotics.github.io" # the base hostname & protocol for your site, e.g. http://example.com

email: sovexu@mailbox.sc.edu
twitter_username: GamecockRobotix
github_username: GamecockRobotics

# Build settings
plugins:
  - jekyll-feed

github: [metadata]

include: [_pages]
